language: en-US

reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: false
  auto_title_placeholder: "@coderabbitai"
  review_status: false
  commit_status: false
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: false
  estimate_code_review_effort: false
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: false
  suggested_reviewers: true
  in_progress_fortune: false
  poem: false
  abort_on_close: true

  path_filters:
    - "!tests/"

  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false

  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false

  pre_merge_checks:
    docstrings:
      mode: off
    title:
      mode: warning
    description:
      mode: warning
    issue_assessment:
      mode: warning

  tools:
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_only: false
      level: default
    yamllint:
      enabled: true
    actionlint:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/.cursor/rules/*.mdc"
      - "**/CONTRIBUTING.md"

